// @generated by tools/gen_area_tiers.py -- DO NOT EDIT BY HAND.
// Source: greenfield/area_tiers.tsv (tools/datamine_area_tiers.py --emit, which needs the MSBs
//         and therefore the Windows box -- AGENTS.md section 5a, tier-2).
// Regenerate: python tools/gen_area_tiers.py
//
// STATIC GAME DATA: what difficulty VANILLA declared for the ground in each play_region bucket,
// measured offline instead of at runtime. 128 buckets emitted, 115 of them with a defensible
// tier; a bucket ABSENT here has no claim and the caller MUST fall back rather than default.

//! Vanilla's own declared difficulty per play_region bucket (issue #346).
//!
//! ## Why this is baked and not measured
//!
//! `scaling::area_tier_from_histogram` counts the enemies that carry a vanilla ladder rung AND a
//! band -- and our own sweep STRIPS the band. So the live census erases its own sample: a region
//! answers `Some(n)` on its first sweep and `None` on every sweep after. That is harmless for the
//! enemies standing there at the time (they come out carrying a rung or a down state, and
//! `Replace`/`KeepDown` re-derive them forever) and fatal for anything that arrives LATER, which
//! has neither. bobler, 2026-08-09: bucket 69300 answered `from 0 vanilla-shaped` on 33 of 48
//! sweeps and its `left vanilla` count never converged -- it plateaued at 122..214.
//!
//! `AreaAnchor` latches the first good live reading and covers most of that. It cannot help a
//! region that never samples well ONCE (bucket 21020: two sweeps, both `from 0`, zero down-states),
//! and it does not survive `configure`, so loading a save into already-converged ground starts the
//! hunt over with no vanilla sample left anywhere in it.
//!
//! This table has neither problem: the ground is a property of the MAP, so it is knowable without
//! a live sample and correct on a region's FIRST sweep.
//!
//! ## How it was derived
//!
//! `mapstudio/<map>-msb-dcx/Part/Enemy/*.xml` -> `NPCParamID` -> `NpcParam.spEffectID3` (the only
//! column in the whole param set that carries a ladder rung: 2952 base rows, 1282 DLC, and
//! `spEffectID0/1/2` carry zero) -> bucket via `play_region_buckets.tsv` -> **the weighted median,
//! using the same reducer as `area_tier_from_histogram`**. A different reducer would make this a
//! second opinion rather than a replacement.
//!
//! ## Validation
//!
//! Reproduced two independent live census readings from static data:
//! **Liurnia (62000) = 5** against a recorded `area-index 5`, and **Altus (63000) = 7** against a
//! recorded `area-index 7` off a 302-enemy sample. Altus was not in the acceptance set.
//!
//! ## Two things to know before using a number from here
//!
//! 1. **A DLC tier and a base tier are NOT comparable to each other.** The two ladders are disjoint
//!    bands -- base spans 1.141x..7.422x HP, the DLC ladder 7.047x..16.641x -- so no multiplier
//!    mapping between them exists. DLC buckets (34 of them, listed in `DLC_RANKED`) are ranked
//!    WITHIN the 16-rung DLC ladder and projected onto 0..19 by RANK. Each is only ever compared
//!    against its own region's sphere target, which is likewise a position and not a multiplier.
//!    Anything that pools the two scales is wrong.
//! 2. **It is a SAMPLE, not a census.** `play_region_buckets.tsv` names a subset of each overworld
//!    bucket's tiles (`PlayRegionParam` does not name the rest; the game resolves play_region by
//!    position at runtime), so 61% of enemy parts land in no bucket at all. The median is robust
//!    to that and two regions matched their live readings, but the skipped set is larger than the
//!    sample.

/// `(play_region bucket, ladder index 0..19)`, sorted so lookup can binary-search.
///
/// ABSENT = NO CLAIM, deliberately, and it is the same convention as `native_tiers::NATIVE_TIERS`:
/// 13 buckets had fewer than `MIN_AREA_SAMPLE` runged enemies and are simply not here.
pub const AREA_TIERS: &[(i32, u8)] = &[
    (10000, 2),
    (11000, 9),
    (11050, 14),
    (12010, 10),
    (12020, 8),
    (12030, 10),
    (12050, 16),
    (12070, 8),
    (13000, 13),
    (14000, 5),
    (15000, 18),
    (16000, 10),
    (18000, 5),
    (20000, 1),
    (20010, 14),
    (21000, 8),
    (21010, 10),
    (21020, 8),
    (22000, 8),
    (25000, 14),
    (30000, 1),
    (30010, 1),
    (30020, 0),
    (30030, 5),
    (30040, 0),
    (30050, 5),
    (30060, 5),
    (30070, 8),
    (30080, 7),
    (30090, 8),
    (30100, 8),
    (30110, 0),
    (30120, 7),
    (30130, 8),
    (30140, 6),
    (30150, 6),
    (30160, 14),
    (30170, 11),
    (30180, 11),
    (30190, 15),
    (30200, 15),
    (31010, 1),
    (31020, 1),
    (31030, 0),
    (31040, 5),
    (31050, 5),
    (31060, 5),
    (31070, 8),
    (31090, 8),
    (31100, 14),
    (31110, 6),
    (31120, 15),
    (31150, 0),
    (31170, 0),
    (31180, 7),
    (31190, 7),
    (31200, 6),
    (31210, 6),
    (31220, 11),
    (32000, 1),
    (32010, 0),
    (32020, 5),
    (32040, 7),
    (32050, 7),
    (32070, 6),
    (32080, 6),
    (32110, 15),
    (34110, 9),
    (34120, 8),
    (34140, 11),
    (35000, 12),
    (39200, 6),
    (40000, 3),
    (40010, 6),
    (40020, 9),
    (41000, 0),
    (41010, 5),
    (41020, 6),
    (42000, 3),
    (42010, 5),
    (42020, 5),
    (42030, 6),
    (43000, 5),
    (43010, 3),
    (61000, 0),
    (61010, 0),
    (61020, 1),
    (62000, 5),
    (62010, 5),
    (62020, 12),
    (63000, 7),
    (63010, 8),
    (63020, 8),
    (64000, 6),
    (64010, 6),
    (64020, 14),
    (65000, 11),
    (65010, 11),
    (65020, 11),
    (65030, 15),
    (68000, 0),
    (68100, 3),
    (68200, 5),
    (68300, 4),
    (68400, 6),
    (68410, 6),
    (68500, 14),
    (68600, 13),
    (69000, 5),
    (69010, 6),
    (69020, 5),
    (69030, 5),
    (69300, 11),
    (69400, 11),
    (69410, 11),
];

/// The buckets above whose tier came from the DLC ladder and was rank-projected. Diagnostic only --
/// nothing should branch on it -- but a future change that wants to compare two tiers needs to be
/// able to see that they may not live on the same scale.
pub const DLC_RANKED: &[i32] = &[
    20000, 20010, 21000, 21010, 21020, 22000, 25000, 40000, 40010, 40020, 41000, 41010, 41020,
    42000, 42010, 42020, 42030, 43000, 43010, 68000, 68100, 68200, 68300, 68400, 68410, 68500,
    68600, 69000, 69010, 69020, 69030, 69300, 69400, 69410,
];
