//! enemy_drop_watch.rs -- release enemy-drop checks by the placement EntityID, so a check pays out
//! when its enemy dies even after enemy randomisation has swapped the occupant (#1000).
//!
//! WHY. A flagged enemy-drop check (`ItemLotParam_enemy.getItemFlagId`) is bound to the enemy's
//! `NpcParam`. matt's enemy rando KEEPS the MSB placement `EntityID` but repoints
//! `ModelName`+`NPCParamID`+`ThinkParamID` to a different enemy, so the swapped occupant rolls its
//! OWN drop table, the flagged lot never rolls, and the check's acquisition flag never fires
//! (confirmed via a matt-randomized seed: EntityID 28000390 c5320->c5240, 12010245 c3330->c5540 --
//! see #1000). The flag path (`detour::CHECK_ITEM_FLAGS`) is therefore dead for these checks under
//! enemization: there is no flag to poll.
//!
//! The EntityID SURVIVES the swap, so it is the stable anchor. Watch the placement's death and
//! release the check regardless of which enemy occupies the slot -- the `boss_felled` defeat-flag
//! discipline, one layer down (a plain enemy instead of an arena boss), and the CharacterDead cousin
//! of #908.
//!
//! PURE SEAM, same stance as `boss_felled`/`sweep_view`: no I/O, no game deps. The client reads which
//! watched EntityIDs are dead this tick and asks this module which AP locations to report. The
//! per-EntityID -> AP-location table below is STATIC GAME DATA (the vanilla placement->drop binding
//! is seed-invariant), baked like [`crate::sweep_boss_names`] so no wire key moves CONTRACT_HASH.

use std::collections::HashMap;
use std::collections::HashSet;

/// @generated by tools/gen_enemy_drop_entities.py (vanilla MSB placement -> flagged enemy-drop
/// check). Sorted by entity_id for binary search. `(placement EntityID, AP location id)`.
///
/// 🛑 PARTIAL: this seed covers the vanilla maps unpacked at generation time. A full regen over the
/// complete vanilla MSB set fills the remaining ~106 flagged enemy-drop checks (147 shipped total).
/// The table is a FALLBACK universe; the client watches only the subset whose AP location is in the
/// seed (see [`build_watch`]).
pub const ENEMY_DROP_ENTITIES: [(u32, i64); 41] = [
    (10000520, 7774017), // Raw Meat Dumpling
    (11000405, 7771124), // Gravel Stone Seal
    (11000469, 7771126), // 1890000
    (11000480, 7771121), // Somber Smithing Stone [4]
    (12010245, 7771237), // Larval Tear
    (12010247, 7771239), // Larval Tear
    (12010256, 7771241), // Larval Tear
    (12020392, 7771345), // 301000
    (14000600, 7774035), // Raw Meat Dumpling
    (14000680, 7771654), // Gravity Well
    (16000500, 7771821), // Great Omenkiller Cleaver
    (16000520, 7771823), // Bloodhound Claws
    (18000330, 7774042), // Dragon Communion Seal
    (20000272, 7771912), // Golden Horn Tender
    (21020270, 7774062), // Raw Meat Dumpling
    (22000450, 7772111), // Congealed Putrescence
    (28000390, 7772123), // Revered Spirit Ash
    (30130400, 7774074), // Raw Meat Dumpling
    (30130402, 7774075), // Raw Meat Dumpling
    (30130407, 7774073), // Raw Meat Dumpling
    (30130408, 7774072), // Raw Meat Dumpling
    (30180326, 7774083), // Raw Meat Dumpling
    (30180350, 7774084), // Raw Meat Dumpling
    (30180351, 7774081), // Raw Meat Dumpling
    (30180352, 7774082), // Raw Meat Dumpling
    (30180355, 7774080), // Raw Meat Dumpling
    (31040300, 7772233), // Golden Rune [6]
    (31110300, 7772272), // Ghost Glovewort [4]
    (35000258, 7772522), // Ghost Glovewort [6]
    (35000369, 7772520), // Omen Bairn
    (35000416, 7772521), // Somber Smithing Stone [7]
    (35000418, 7774101), // Raw Meat Dumpling
    (39200350, 7774121), // Golden Rune [6]
    (39200352, 7774120), // Golden Rune [6]
    (39200353, 7774119), // Golden Rune [6]
    (40020290, 7774158), // Great Ghost Glovewort
    (41000353, 7774171), // Raw Meat Dumpling
    (41000359, 7774169), // Raw Meat Dumpling
    (41000360, 7774168), // Raw Meat Dumpling
    (41010331, 7774179), // Raw Meat Dumpling
    (41010337, 7774177), // Raw Meat Dumpling
];

/// AP location a placement EntityID drops, if it is a known flagged enemy-drop check.
pub fn location_for_entity(entity_id: u32) -> Option<i64> {
    ENEMY_DROP_ENTITIES
        .binary_search_by_key(&entity_id, |&(e, _)| e)
        .ok()
        .map(|i| ENEMY_DROP_ENTITIES[i].1)
}

/// Build the per-seed watch map: the baked table intersected with the locations THIS seed actually
/// ships (`is_seed_location(loc)`). The client calls this once at connect; watching a location the
/// seed does not contain would stage a report the server rejects.
pub fn build_watch<F: Fn(i64) -> bool>(is_seed_location: F) -> HashMap<u32, i64> {
    ENEMY_DROP_ENTITIES
        .iter()
        .copied()
        .filter(|&(_, loc)| is_seed_location(loc))
        .collect()
}

/// Release decision, reconnect-safe. `now_dead` = watched EntityIDs observed dead THIS tick;
/// `prev_dead` = those already seen dead in a prior tick (so a reconnect that re-observes a corpse
/// does not re-stage). Returns the AP locations to stage for the alive->dead EDGE only, de-duplicated
/// and skipping any `is_reported(loc)` already in the server checked-set.
///
/// Mirrors [`crate::boss_felled::newly_felled`]: monotone, edge-triggered, idempotent under replay.
pub fn newly_released<F: Fn(i64) -> bool>(
    watch: &HashMap<u32, i64>,
    prev_dead: &HashSet<u32>,
    now_dead: &HashSet<u32>,
    is_reported: F,
) -> Vec<i64> {
    let mut out: Vec<i64> = Vec::new();
    for &e in now_dead.difference(prev_dead) {
        if let Some(&loc) = watch.get(&e) {
            if !is_reported(loc) && !out.contains(&loc) {
                out.push(loc);
            }
        }
    }
    out.sort_unstable();
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_sorted_and_unique_by_entity() {
        assert!(ENEMY_DROP_ENTITIES.windows(2).all(|w| w[0].0 < w[1].0));
    }

    #[test]
    fn a_known_placement_resolves_its_check() {
        // EntityID 12010245 is a c3330 Larval-Tear dropper (vanilla), AP 7771237. Confirmed #1000.
        assert_eq!(location_for_entity(12010245), Some(7771237));
        assert_eq!(location_for_entity(1), None);
    }

    #[test]
    fn build_watch_keeps_only_seed_locations() {
        let seed: HashSet<i64> = [7771237_i64].into_iter().collect();
        let w = build_watch(|l| seed.contains(&l));
        assert_eq!(w.get(&12010245), Some(&7771237));
        assert!(!w.values().any(|&l| l != 7771237));
    }

    #[test]
    fn releases_on_the_alive_to_dead_edge_only() {
        let w: HashMap<u32, i64> = [(12010245u32, 7771237i64)].into_iter().collect();
        let prev: HashSet<u32> = HashSet::new();
        let now: HashSet<u32> = [12010245u32].into_iter().collect();
        assert_eq!(newly_released(&w, &prev, &now, |_| false), vec![7771237]);
        // already seen dead last tick -> no re-stage
        assert_eq!(newly_released(&w, &now, &now, |_| false), Vec::<i64>::new());
        // already reported -> skipped even on the edge
        assert_eq!(newly_released(&w, &prev, &now, |_| true), Vec::<i64>::new());
    }

    #[test]
    fn an_unwatched_dead_entity_releases_nothing() {
        let w: HashMap<u32, i64> = HashMap::new();
        let now: HashSet<u32> = [999999u32].into_iter().collect();
        assert_eq!(
            newly_released(&w, &HashSet::new(), &now, |_| false),
            Vec::<i64>::new()
        );
    }
}
