// @generated by tools/gen_merchant_bells.py -- DO NOT EDIT BY HAND.
// Source: greenfield/bell_handins.tsv (tools/datamine_bell_handins.py, from the Twin
// Maiden Husks' own talk ESD t600001110).
// Regenerate: python tools/gen_merchant_bells.py   (AP-env-free, pure greenfield data)
//
// STATIC GAME DATA: a merchant's ShopLineupParam row range -> the event flag the Twin
// Maidens set when you hand them that merchant's Bell Bearing. Seed-invariant, so it is
// baked rather than carried in slot_data -- a new wire key would move CONTRACT_HASH to
// ship a constant.

/// `(shop_begin, shop_end, handin_flag, bell_name)`, sorted by `shop_begin` and pairwise
/// disjoint (the generator refuses to emit an overlap).
///
/// 🛑 THE RANGE IS THE MERCHANT'S OWN BLOCK, not a copy of it. Handing a bell to the Twin
/// Maidens adds a MENU ENTRY pointing at these same rows; it does not release or duplicate
/// stock. That is why setting `handin_flag` is the whole mechanism, and why the AP check on
/// a row fires identically whether it was bought at the merchant or at the hub -- the row,
/// and therefore its `eventFlag_forStock`, is the same row.
pub const MERCHANT_BELLS: [(i32, i32, u32, &str); 38] = [
    (100000, 100024, 11109718, "Gostoc's Bell Bearing"),
    (100050, 100074, 11109713, "Sellen's Bell Bearing"),
    (100075, 100099, 11109716, "Bernahl's Bell Bearing"),
    (100100, 100124, 11109712, "Patches' Bell Bearing"),
    (100125, 100149, 11109715, "D's Bell Bearing"),
    (100150, 100174, 11109742, "Blackguard's Bell Bearing"),
    (100175, 100184, 11109744, "Gowry's Bell Bearing"),
    (100185, 100199, 11109744, "Gowry's Bell Bearing"),
    (100200, 100224, 11109741, "Rogier's Bell Bearing"),
    (100225, 100249, 11109740, "Iji's Bell Bearing"),
    (100250, 100274, 11109719, "Thops's Bell Bearing"),
    (100275, 100299, 11109711, "Seluvis's Bell Bearing"),
    (100325, 100349, 11109710, "Pidia's Bell Bearing"),
    (100350, 100399, 11109743, "Corhyn's Bell Bearing"),
    (100400, 100424, 11109717, "Miriel's Bell Bearing"),
    (100425, 100474, 11109717, "Miriel's Bell Bearing"),
    (100500, 100524, 11109720, "Kale's Bell Bearing"),
    (100525, 100549, 11109721, "Nomadic Merchant's Bell Bearing [1]"),
    (100550, 100574, 11109722, "Nomadic Merchant's Bell Bearing [2]"),
    (100575, 100599, 11109723, "Nomadic Merchant's Bell Bearing [3]"),
    (100600, 100624, 11109724, "Nomadic Merchant's Bell Bearing [4]"),
    (100625, 100649, 11109725, "Nomadic Merchant's Bell Bearing [5]"),
    (100650, 100674, 11109726, "Isolated Merchant's Bell Bearing [1]"),
    (100675, 100699, 11109727, "Isolated Merchant's Bell Bearing [2]"),
    (100700, 100724, 11109728, "Nomadic Merchant's Bell Bearing [6]"),
    (100725, 100749, 11109729, "Hermit Merchant's Bell Bearing [1]"),
    (100750, 100774, 11109730, "Nomadic Merchant's Bell Bearing [7]"),
    (100775, 100799, 11109731, "Nomadic Merchant's Bell Bearing [8]"),
    (100800, 100824, 11109732, "Nomadic Merchant's Bell Bearing [9]"),
    (100825, 100849, 11109733, "Nomadic Merchant's Bell Bearing [10]"),
    (100850, 100874, 11109734, "Nomadic Merchant's Bell Bearing [11]"),
    (100875, 100899, 11109735, "Isolated Merchant's Bell Bearing [3]"),
    (100900, 100924, 11109736, "Hermit Merchant's Bell Bearing [2]"),
    (100925, 100949, 11109737, "Abandoned Merchant's Bell Bearing"),
    (100950, 100974, 11109738, "Hermit Merchant's Bell Bearing [3]"),
    (100975, 100999, 11109739, "Imprisoned Merchant's Bell Bearing"),
    (102250, 102289, 11109790, "Moore's Bell Bearing"),
    (102300, 102310, 11109791, "Ymir's Bell Bearing"),
];

/// The bell whose merchant owns `[begin, end]`, if any.
///
/// Matches by CONTAINMENT, not equality. A merchant can open a narrower slice of its own
/// block than the Twin Maidens do (Moore's talk opens `102270..102289` where the Maidens'
/// entry opens `102250..102289`), and because the table's ranges are pairwise disjoint the
/// containing range is unique when it exists.
pub fn bell_for_range(begin: i32, end: i32) -> Option<(u32, &'static str)> {
    if begin > end {
        return None;
    }
    let i = MERCHANT_BELLS.partition_point(|&(lo, _, _, _)| lo <= begin);
    let (lo, hi, flag, name) = *MERCHANT_BELLS.get(i.checked_sub(1)?)?;
    (lo <= begin && end <= hi).then_some((flag, name))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `bell_for_range` binary-searches, and the generator sorts -- a hand edit would not.
    #[test]
    fn the_table_is_sorted_and_disjoint() {
        assert!(MERCHANT_BELLS.windows(2).all(|w| w[0].1 < w[1].0));
        assert!(MERCHANT_BELLS.iter().all(|&(lo, hi, _, _)| lo <= hi));
    }

    /// Toast text is drawn by the GAME's font, which has no glyph for non-ASCII.
    #[test]
    fn every_name_is_ascii() {
        for (_, _, flag, name) in MERCHANT_BELLS {
            assert!(name.is_ascii(), "flag {flag} name {name:?} is not ASCII");
        }
    }

    #[test]
    fn every_range_resolves_to_its_own_bell() {
        for (lo, hi, flag, _) in MERCHANT_BELLS {
            assert_eq!(bell_for_range(lo, hi).map(|(f, _)| f), Some(flag));
        }
    }

    /// A merchant may open a narrower slice than the Maidens' entry does.
    #[test]
    fn a_contained_range_resolves() {
        let (lo, hi, flag, _) = MERCHANT_BELLS[0];
        assert_eq!(bell_for_range(lo, hi.min(lo + 1)).map(|(f, _)| f), Some(flag));
    }

    /// The Twin Maidens' OWN buy menu (101800..101897) is not a merchant with a bell, and
    /// it is the range the 2026-08-08 probe actually observed -- so it is the one open that
    /// must resolve to nothing.
    #[test]
    fn the_twin_maidens_own_shelf_has_no_bell() {
        assert_eq!(bell_for_range(101_800, 101_897), None);
    }

    #[test]
    fn a_range_wider_than_its_block_is_refused() {
        let (lo, hi, _, _) = MERCHANT_BELLS[0];
        assert_eq!(bell_for_range(lo, hi + 1), None);
        assert_eq!(bell_for_range(hi, lo), None);
    }
}
