// @generated by tools/gen_region_locks.py -- DO NOT EDIT BY HAND.
// Sources: greenfield/eldenring/region_open_flags.py (REGION_OPEN_FLAGS) +
//          greenfield/eldenring/features/area_locks.py (REGION_PLAY_IDS).
// Regenerate: python tools/gen_region_locks.py   (AP-env-free, pure greenfield data)
//
// STATIC GAME DATA: region -> warp-grace open flag + play_region geometry. Seed-invariant;
// the only per-seed input is which "<Region> Lock" items exist. slot_data (areaLockFlags /
// regionOpenFlags) always WINS when present -- this table only feeds the foreign-apworld
// fallback (er_logic::region_lock::derive_region_locks).

/// One baked region: its lock-item name, warp-grace open flag (None = geometry known but no
/// resolved open flag, so the region cannot be gated), and its play_region ids.
pub struct BakedRegionLock {
    pub region: &'static str,
    pub lock_item: &'static str,
    pub open_flag: Option<u32>,
    pub play_regions: &'static [i32],
}

/// All baked regions, sorted by region name. play_region ids are globally unique
/// (generator-enforced), so a range derived per id can never point at two regions.
pub const REGION_LOCKS: &[BakedRegionLock] = &[
    BakedRegionLock {
        region: "Abyssal Woods",
        lock_item: "Abyssal Woods Lock",
        open_flag: Some(72801),
        play_regions: &[6860, 28000],
    },
    BakedRegionLock {
        region: "Altus Plateau",
        lock_item: "Altus Plateau Lock",
        open_flag: Some(73204),
        play_regions: &[63000, 63002, 63003],
    },
    BakedRegionLock {
        region: "Ancient Ruins of Rauh",
        lock_item: "Ancient Ruins of Rauh Lock",
        open_flag: Some(76803),
        play_regions: &[6950],
    },
    BakedRegionLock {
        region: "Belurat",
        lock_item: "Belurat Lock",
        open_flag: Some(72001),
        play_regions: &[20000],
    },
    BakedRegionLock {
        region: "Caelid",
        lock_item: "Caelid Lock",
        open_flag: Some(73207),
        play_regions: &[64000, 64001, 64002],
    },
    BakedRegionLock {
        region: "Enir-Ilim",
        lock_item: "Enir-Ilim Lock",
        open_flag: Some(72012),
        play_regions: &[20010],
    },
    BakedRegionLock {
        region: "Eternal Cities",
        lock_item: "Eternal Cities Lock",
        open_flag: Some(71211),
        play_regions: &[12010, 12011, 12012, 12020, 12030, 12070],
    },
    BakedRegionLock {
        region: "Farum Azula",
        lock_item: "Farum Azula Lock",
        open_flag: Some(71303),
        play_regions: &[13000],
    },
    BakedRegionLock {
        region: "Gravesite Plain",
        lock_item: "Gravesite Plain Lock",
        open_flag: Some(76800),
        play_regions: &[6800, 6820, 6830, 6840, 22000],
    },
    BakedRegionLock {
        region: "Jagged Peak",
        lock_item: "Jagged Peak Lock",
        open_flag: Some(76850),
        play_regions: &[6850, 6851],
    },
    BakedRegionLock {
        region: "Leyndell",
        lock_item: "Leyndell Lock",
        open_flag: None,
        play_regions: &[11000, 11050, 35000, 19000],
    },
    BakedRegionLock {
        region: "Limgrave",
        lock_item: "Limgrave Lock",
        open_flag: Some(73100),
        play_regions: &[61000, 61001],
    },
    BakedRegionLock {
        region: "Liurnia of the Lakes",
        lock_item: "Liurnia of the Lakes Lock",
        open_flag: Some(73202),
        play_regions: &[62000, 62001, 62002],
    },
    BakedRegionLock {
        region: "Miquella's Haligtree",
        lock_item: "Miquella's Haligtree Lock",
        open_flag: Some(71501),
        play_regions: &[15000, 15001],
    },
    BakedRegionLock {
        region: "Mohgwyn Palace",
        lock_item: "Mohgwyn Palace Lock",
        open_flag: Some(71251),
        play_regions: &[12050],
    },
    BakedRegionLock {
        region: "Mountaintops of the Giants",
        lock_item: "Mountaintops of the Giants Lock",
        open_flag: Some(73017),
        play_regions: &[65000, 65001, 65002],
    },
    BakedRegionLock {
        region: "Mt. Gelmir",
        lock_item: "Mt. Gelmir Lock",
        open_flag: Some(76350),
        play_regions: &[63001, 16000, 39200],
    },
    BakedRegionLock {
        region: "Raya Lucaria Academy",
        lock_item: "Raya Lucaria Academy Lock",
        open_flag: None,
        play_regions: &[14000],
    },
    BakedRegionLock {
        region: "Scadu Altus",
        lock_item: "Scadu Altus Lock",
        open_flag: Some(76834),
        play_regions: &[6900, 6920, 6940],
    },
    BakedRegionLock {
        region: "Shadow Keep",
        lock_item: "Shadow Keep Lock",
        open_flag: Some(72102),
        play_regions: &[21000, 21001, 21010],
    },
    BakedRegionLock {
        region: "Stormveil Castle",
        lock_item: "Stormveil Castle Lock",
        open_flag: Some(71002),
        play_regions: &[10000],
    },
    BakedRegionLock {
        region: "Weeping Peninsula",
        lock_item: "Weeping Peninsula Lock",
        open_flag: Some(73102),
        play_regions: &[61002],
    },
];

/// Look a lock-item NAME (e.g. "Caelid Lock") up in the baked table.
pub fn by_lock_item(name: &str) -> Option<&'static BakedRegionLock> {
    REGION_LOCKS.iter().find(|r| r.lock_item == name)
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn nonempty_sorted_unique() {
        assert!(!REGION_LOCKS.is_empty());
        assert!(REGION_LOCKS.windows(2).all(|w| w[0].region < w[1].region));
        let mut ids: Vec<i32> = REGION_LOCKS.iter().flat_map(|r| r.play_regions.iter().copied()).collect();
        let n = ids.len();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), n, "play_region ids must be globally unique");
        assert!(REGION_LOCKS.iter().all(|r| !r.play_regions.is_empty()));
    }

    #[test]
    fn lock_items_follow_the_naming_convention() {
        for r in REGION_LOCKS {
            assert_eq!(r.lock_item, format!("{} Lock", r.region));
            assert!(by_lock_item(r.lock_item).is_some());
        }
        assert!(by_lock_item("No Such Region Lock").is_none());
    }
}
