// @generated by tools/gen_region_locks.py -- DO NOT EDIT BY HAND.
// Sources: greenfield/eldenring/region_open_flags.py (REGION_OPEN_FLAGS) +
//          greenfield/eldenring/features/area_locks.py (REGION_PLAY_IDS).
// Regenerate: python tools/gen_region_locks.py   (AP-env-free, pure greenfield data)
//
// STATIC GAME DATA: region -> warp-grace open flag + play_region geometry. Seed-invariant;
// the only per-seed input is which "<Region> Lock" items exist. slot_data (areaLockFlags /
// regionOpenFlags) always WINS when present -- this table only feeds the foreign-apworld
// fallback (er_logic::region_lock::derive_region_locks).

/// One baked region: its lock-item name, warp-grace open flag (None = geometry known but no
/// resolved open flag, so the region cannot be gated), and its play_region ids.
pub struct BakedRegionLock {
    pub region: &'static str,
    pub lock_item: &'static str,
    pub open_flag: Option<u32>,
    pub play_regions: &'static [i32],
}

/// All baked regions, sorted by region name. play_region ids are globally unique
/// (generator-enforced), so a range derived per id can never point at two regions.
pub const REGION_LOCKS: &[BakedRegionLock] = &[
    BakedRegionLock {
        region: "Abyssal",
        lock_item: "Abyssal Lock",
        open_flag: Some(76860),
        play_regions: &[6860, 28000],
    },
    BakedRegionLock {
        region: "Ainsel River",
        lock_item: "Ainsel River Lock",
        open_flag: Some(71211),
        play_regions: &[12010, 12011, 12012],
    },
    BakedRegionLock {
        region: "Altus",
        lock_item: "Altus Lock",
        open_flag: Some(73204),
        play_regions: &[63000, 63002, 63003],
    },
    BakedRegionLock {
        region: "Ancient Ruins",
        lock_item: "Ancient Ruins Lock",
        open_flag: Some(76940),
        play_regions: &[6940],
    },
    BakedRegionLock {
        region: "Belurat",
        lock_item: "Belurat Lock",
        open_flag: Some(72001),
        play_regions: &[20000],
    },
    BakedRegionLock {
        region: "Caelid",
        lock_item: "Caelid Lock",
        open_flag: Some(73207),
        play_regions: &[64000, 64001, 64002],
    },
    BakedRegionLock {
        region: "Cerulean",
        lock_item: "Cerulean Lock",
        open_flag: Some(76831),
        play_regions: &[6830],
    },
    BakedRegionLock {
        region: "Charo's",
        lock_item: "Charo's Lock",
        open_flag: Some(76841),
        play_regions: &[6840],
    },
    BakedRegionLock {
        region: "Deeproot Depths",
        lock_item: "Deeproot Depths Lock",
        open_flag: Some(71231),
        play_regions: &[12030],
    },
    BakedRegionLock {
        region: "Enir Ilim",
        lock_item: "Enir Ilim Lock",
        open_flag: Some(72012),
        play_regions: &[20010],
    },
    BakedRegionLock {
        region: "Ensis",
        lock_item: "Ensis Lock",
        open_flag: Some(76821),
        play_regions: &[6820],
    },
    BakedRegionLock {
        region: "Farum Azula",
        lock_item: "Farum Azula Lock",
        open_flag: Some(71303),
        play_regions: &[13000],
    },
    BakedRegionLock {
        region: "Gravesite",
        lock_item: "Gravesite Lock",
        open_flag: Some(76800),
        play_regions: &[6800],
    },
    BakedRegionLock {
        region: "Haligtree",
        lock_item: "Haligtree Lock",
        open_flag: Some(71501),
        play_regions: &[15000, 15001],
    },
    BakedRegionLock {
        region: "Jagged Peak",
        lock_item: "Jagged Peak Lock",
        open_flag: Some(76840),
        play_regions: &[6850, 6851],
    },
    BakedRegionLock {
        region: "Leyndell",
        lock_item: "Leyndell Lock",
        open_flag: Some(71102),
        play_regions: &[11000, 11050, 19000],
    },
    BakedRegionLock {
        region: "Limgrave",
        lock_item: "Limgrave Lock",
        open_flag: Some(73100),
        play_regions: &[61000, 61001],
    },
    BakedRegionLock {
        region: "Liurnia",
        lock_item: "Liurnia Lock",
        open_flag: Some(73202),
        play_regions: &[39200, 62000, 62001, 62002],
    },
    BakedRegionLock {
        region: "Mohgwyn",
        lock_item: "Mohgwyn Lock",
        open_flag: Some(71251),
        play_regions: &[12050],
    },
    BakedRegionLock {
        region: "Mountaintops of the Giants",
        lock_item: "Mountaintops of the Giants Lock",
        open_flag: Some(73017),
        play_regions: &[65000, 65001, 65002],
    },
    BakedRegionLock {
        region: "Mt. Gelmir",
        lock_item: "Mt. Gelmir Lock",
        open_flag: Some(76350),
        play_regions: &[16000, 63001],
    },
    BakedRegionLock {
        region: "Rauh Base",
        lock_item: "Rauh Base Lock",
        open_flag: Some(76912),
        play_regions: &[6950],
    },
    BakedRegionLock {
        region: "Raya Lucaria Academy",
        lock_item: "Raya Lucaria Academy Lock",
        open_flag: Some(71402),
        play_regions: &[14000],
    },
    BakedRegionLock {
        region: "Scadu Altus",
        lock_item: "Scadu Altus Lock",
        open_flag: Some(76900),
        play_regions: &[6900],
    },
    BakedRegionLock {
        region: "Scaduview",
        lock_item: "Scaduview Lock",
        open_flag: Some(76935),
        play_regions: &[6920],
    },
    BakedRegionLock {
        region: "Sewer",
        lock_item: "Sewer Lock",
        open_flag: Some(73501),
        play_regions: &[35000],
    },
    BakedRegionLock {
        region: "Shadow Keep",
        lock_item: "Shadow Keep Lock",
        open_flag: Some(72102),
        play_regions: &[21000, 21001, 21010],
    },
    BakedRegionLock {
        region: "Siofra River",
        lock_item: "Siofra River Lock",
        open_flag: Some(71222),
        play_regions: &[12020, 12070],
    },
    BakedRegionLock {
        region: "Stone Coffin",
        lock_item: "Stone Coffin Lock",
        open_flag: Some(72201),
        play_regions: &[22000],
    },
    BakedRegionLock {
        region: "Stormveil",
        lock_item: "Stormveil Lock",
        open_flag: Some(71003),
        play_regions: &[10000],
    },
    BakedRegionLock {
        region: "Weeping",
        lock_item: "Weeping Lock",
        open_flag: Some(73102),
        play_regions: &[61002],
    },
];

/// Look a lock-item NAME (e.g. "Caelid Lock") up in the baked table.
pub fn by_lock_item(name: &str) -> Option<&'static BakedRegionLock> {
    REGION_LOCKS.iter().find(|r| r.lock_item == name)
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn nonempty_sorted_unique() {
        assert!(!REGION_LOCKS.is_empty());
        assert!(REGION_LOCKS.windows(2).all(|w| w[0].region < w[1].region));
        let mut ids: Vec<i32> = REGION_LOCKS.iter().flat_map(|r| r.play_regions.iter().copied()).collect();
        let n = ids.len();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), n, "play_region ids must be globally unique");
        assert!(REGION_LOCKS.iter().all(|r| !r.play_regions.is_empty()));
    }

    #[test]
    fn lock_items_follow_the_naming_convention() {
        for r in REGION_LOCKS {
            assert_eq!(r.lock_item, format!("{} Lock", r.region));
            assert!(by_lock_item(r.lock_item).is_some());
        }
        assert!(by_lock_item("No Such Region Lock").is_none());
    }
}
