//! Resolve AP location ids -> in-game acquisition event flags from the matt-rando slot
//! key table `locationIdsToKeys`, replacing the legacy `locationFlags` `{loc: flag}` table.
//!
//! Bedrock's apworld emits (net slot_data):
//!   locationIdsToKeys     = { "<ap_location_id>": "<a>,<b>:<flag>:<shopRows>:" }
//!   "locationIdsToTargets " = { "<ap_location_id>": ["lot:NNNN"|"shop:NNNN", ...] }
//! NB the trailing SPACE in the second key name is REAL -- measured in its fill_slot_data
//! (fswap/Archipelago@er, worlds/eldenring/__init__.py, `"locationIdsToTargets ":`); we accept
//! both spellings so a future typo fix over there costs nothing here.
//!
//! The KEY already encodes the acquisition event flag as token 1 (`key.split(':')[1]`) --
//! verified equal to ItemLotParam getItemFlagId for ~94% of slots. So the primary path is a
//! pure string split, no param files. Shop slots (token1 == 0, token3 = ShopLineupParam rows)
//! carry no acquisition flag; [`shop_flags_from_keys`] resolves them -- token3 row ->
//! eventFlag_forStock via the shipped `shoplineup_flags.json` ([`load_shoplineup_flags`]; the
//! table is generated by the apworld's `tools/gen_shoplineup_flags.py`) -- and `core.rs` folds
//! the result into the same poll map (see "SHOP KEY RESOLUTION"). Nothing here is deferred.
//!
//! Output is the SAME `HashMap<i64, u32>` `{ap_location_id: flag}` shape the client already
//! polls (see `flagpoll::FlagPollConfig::location_flags`), so it drops in where `locationFlags`
//! was consumed. std + serde_json only; mirrors `core::i64_to_u32_map` tolerance.

use std::collections::HashMap;

use serde_json::Value;

/// Token 1 of a matt slot key = the acquisition event flag (0 if none / shop).
/// Mirrors the Python `_key_flag`: strip leading zeros to detect the all-zero placeholder,
/// then parse the raw token as u32. Returns None when there is no usable flag.
fn key_flag(key: &str) -> Option<u32> {
    let tok1 = key.split(':').nth(1)?.trim();
    // "0000000000" (all zeros) is the shop/no-flag placeholder -> treat as absent.
    if tok1.trim_matches('0').is_empty() {
        return None;
    }
    tok1.parse::<u32>().ok().filter(|&f| f != 0)
}

/// Read `locationIdsToKeys` -> `{ap_location_id: acquisition_flag}`.
///
/// Same shape/semantics as the old `i64_to_u32_map(sd.get("locationFlags"))`, so callers keep
/// polling identically. Slots whose key carries no flag (token1 == 0 / shop rows in token3) are
/// skipped -- deferred to the shop system, matching `resolve_location_flags`'s `shops`/`unresolved`
/// buckets. Tolerant: malformed loc ids or keys are skipped rather than failing the parse.
///
/// Backward-compat is the caller's job: prefer this when `locationIdsToKeys` is present, else fall
/// back to `locationFlags` (see core_rs_integration.md).
pub fn location_flags_from_keys(sd: &Value) -> HashMap<i64, u32> {
    let mut out = HashMap::new();
    let Some(obj) = sd.get("locationIdsToKeys").and_then(|v| v.as_object()) else {
        return out;
    };
    for (k, v) in obj {
        let (Ok(loc), Some(key)) = (k.parse::<i64>(), v.as_str()) else {
            continue;
        };
        if let Some(flag) = key_flag(key) {
            out.insert(loc, flag);
        }
        // else: shop (token1 == 0) or unresolved -> deferred, not polled by flag.
    }
    out
}

/// Token 3 of a matt slot key = ShopLineupParam row ids (present only for shop slots,
/// where token1 == 0). Mirrors the Python `_key_shop_rows`: split token3 on ',',
/// keep the all-digit entries. Empty for non-shop keys.
fn key_shop_rows(key: &str) -> Vec<u32> {
    match key.split(':').nth(2) {
        Some(tok3) if !tok3.trim().is_empty() => tok3
            .split(',')
            .filter_map(|x| {
                let x = x.trim();
                if !x.is_empty() && x.bytes().all(|b| b.is_ascii_digit()) {
                    x.parse::<u32>().ok()
                } else {
                    None
                }
            })
            .collect(),
        _ => Vec::new(),
    }
}

/// Resolve SHOP location ids -> check event flags, using `locationIdsToKeys` (from
/// slot_data) and a loaded `{shop_row_id: eventFlag_forStock}` table (the shipped
/// `shoplineup_flags.json`, generated by the apworld's `tools/gen_shoplineup_flags.py`).
///
/// A shop slot has key token1 == 0 (no acquisition flag) and its ShopLineupParam row
/// ids in token 3, e.g. `"100000,0:0000000000:100200:"` -> rows [100200]. The check
/// flag for a row is its `eventFlag_forStock` -- verified 100% (649/649) equal to
/// matt's shop tracking flags. So a shop slot resolves to the FIRST of its token3 rows
/// that has a flag in `row_flags`.
///
/// Output is the SAME `HashMap<i64, u32>` `{ap_location_id: flag}` shape as
/// [`location_flags_from_keys`], so the two can be merged into ONE poll map (`loc_flags`)
/// and shop purchases self-detect through the existing flag poller. Only slots whose
/// key carries NO acquisition flag (token1 == 0) are considered here -- flagged slots
/// are already handled by [`location_flags_from_keys`], so this never double-inserts.
/// Rows absent from `row_flags` (stock flag 0 / not in the shipped table) are skipped;
/// the slot stays unresolved (unpolled) rather than being polled on a bogus flag.
///
/// TOKEN3 NON-ROWS + THE TARGETS FALLBACK (measured 2026-07-12, static parse of the foreign
/// world's own location table, fswap/Archipelago@er @6058820): token3 can also carry a
/// precondition EVENT FLAG (a boss-achievement gate) or a shop-range BASE id alongside -- or
/// instead of -- a concrete row. Non-row entries are naturally skipped (never in `row_flags`).
/// Of 583 distinct shop slots, 476 resolve from token3; of the 107 that do not, 43 carry a
/// concrete row in the targets table as `"shop:NNNN"` -- those now resolve through
/// [`targets_shop_rows`], same first-flagged-row rule. The remaining 64 (one merchant's
/// boss-armor group: token3 = achievement flag + shop-range BASE id, e.g. 101500, and NO
/// targets entry) carry nothing that names a ShopLineupParam row, so they stay unpolled --
/// a KNOWN LIMIT, not a bug to paper over. (In a generated seed the world also mints duplicate
/// shop locations sharing these keys, which is how the earlier in-seed measurement read
/// 637 total / 520 resolved: same table + 54 duplicates.)
///
/// Mirrors the Python `resolve_location_flags`'s `shops` bucket + `shop_row_flags_for`
/// composed: token3 rows -> ShopLineupParam eventFlag_forStock -> flag.
pub fn shop_flags_from_keys(sd: &Value, row_flags: &HashMap<u32, u32>) -> HashMap<i64, u32> {
    let mut out = HashMap::new();
    let Some(obj) = sd.get("locationIdsToKeys").and_then(|v| v.as_object()) else {
        return out;
    };
    // The targets table (see the module doc for the trailing-space key: both spellings accepted,
    // exact name first so a future fix wins).
    let targets = sd
        .get("locationIdsToTargets")
        .or_else(|| sd.get("locationIdsToTargets "));
    let first_flagged = |rows: Vec<u32>| -> Option<u32> {
        rows.into_iter()
            .find_map(|row| row_flags.get(&row).copied().filter(|&f| f != 0))
    };
    for (k, v) in obj {
        let (Ok(loc), Some(key)) = (k.parse::<i64>(), v.as_str()) else {
            continue;
        };
        // Only shop slots: token1 == 0 (no acquisition flag). Flagged slots are owned by
        // `location_flags_from_keys`; skipping them here keeps the two maps disjoint.
        if key_flag(key).is_some() {
            continue;
        }
        // First token3 row that has a stock flag in the shipped table wins. (A shop slot
        // maps to one check; the extra rows in token3, when present, share the same stock
        // flag or are release-only rows -- the first flagged one is the check flag.) When
        // token3 names no known row (precondition flag / shop-range base only), fall back to
        // the slot's targets `"shop:NNNN"` rows -- same rule.
        let flag = first_flagged(key_shop_rows(key))
            .or_else(|| first_flagged(targets_shop_rows(targets, k)));
        if let Some(flag) = flag {
            out.insert(loc, flag);
        }
    }
    out
}

/// The `"shop:NNNN"` ShopLineupParam rows a slot's targets entry names. Non-shop entries
/// (`"lot:NNNN"` item lots) are skipped. Tolerates the source's shapes: an array of strings is
/// the emitted form, a bare string is the un-normalized form its location table also contains
/// (a one-element tuple written without the comma) -- cheap to accept, so accept it.
fn targets_shop_rows(targets: Option<&Value>, loc_key: &str) -> Vec<u32> {
    let Some(entry) = targets.and_then(|t| t.get(loc_key)) else {
        return Vec::new();
    };
    fn parse_one(s: &str) -> Option<u32> {
        s.trim()
            .strip_prefix("shop:")
            .and_then(|r| r.parse::<u32>().ok())
    }
    match entry {
        Value::String(s) => parse_one(s).into_iter().collect(),
        Value::Array(a) => a
            .iter()
            .filter_map(|v| v.as_str())
            .filter_map(parse_one)
            .collect(),
        _ => Vec::new(),
    }
}

/// Load the shipped `shoplineup_flags.json` -> `{shop_row_id: eventFlag_forStock}`.
/// Same tolerant shape as `flagpoll::merge_table_file`: a flat JSON object of
/// string-int-keyed integer values. Missing/invalid file -> empty map (shops simply
/// stay unresolved, no panic). Same tolerant-merge shape flagpoll uses for its own tables
/// in `flagpoll.rs` (read_to_string -> serde_json -> tolerant object walk).
pub fn load_shoplineup_flags(path: &std::path::Path) -> HashMap<u32, u32> {
    let mut out = HashMap::new();
    let Ok(text) = std::fs::read_to_string(path) else {
        return out;
    };
    // Tolerate any null-padding a shrinking overwrite may leave (mirrors the Python loader).
    let text = text.trim_end_matches('\u{0}').trim_end();
    let Ok(v) = serde_json::from_str::<Value>(text) else {
        return out;
    };
    if let Some(obj) = v.as_object() {
        for (k, val) in obj {
            if let (Ok(row), Some(flag)) = (k.parse::<u32>(), val.as_u64())
                && flag != 0
            {
                out.insert(row, flag as u32);
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn key_token1_is_the_flag() {
        // Real matt-key shape: token 1 (after first ':') is the acquisition flag.
        assert_eq!(key_flag("100000,0:0000060510::"), Some(60510));
        assert_eq!(key_flag("2,1:60110:100000,100001:"), Some(60110));
        // Shop placeholder: token1 all-zero, token3 = shop rows -> no flag.
        assert_eq!(key_flag("100000,0:0000000000:100000:"), None);
        // Degenerate / missing token -> None.
        assert_eq!(key_flag("100000,0"), None);
        assert_eq!(key_flag(""), None);
    }

    #[test]
    fn resolves_table_and_skips_shops() {
        let sd = json!({
            "locationIdsToKeys": {
                "5001": "100000,0:0000060510::",         // flagged -> 60510
                "5002": "2,1:60110:100000,100001:",       // flagged -> 60110
                "5003": "100000,0:0000000000:100000:",    // shop    -> skipped
            }
        });
        let m = location_flags_from_keys(&sd);
        assert_eq!(m.len(), 2);
        assert_eq!(m.get(&5001), Some(&60510u32));
        assert_eq!(m.get(&5002), Some(&60110u32));
        assert!(!m.contains_key(&5003)); // shop deferred
    }

    #[test]
    fn absent_table_is_empty() {
        // No locationIdsToKeys -> empty map, so the caller falls back to locationFlags.
        assert!(location_flags_from_keys(&json!({})).is_empty());
        assert!(location_flags_from_keys(&json!({ "locationFlags": { "1": 60510 } })).is_empty());
    }

    // --- shop resolution -----------------------------------------------------

    #[test]
    fn key_token3_is_shop_rows() {
        // Real shop key: token1 == 0 (all-zero placeholder), token3 = shop rows.
        assert_eq!(key_shop_rows("100000,0:0000000000:100200:"), vec![100200]);
        // Multiple rows, comma-separated.
        assert_eq!(
            key_shop_rows("1,0:0000000000:100200,100201:"),
            vec![100200, 100201]
        );
        // Flagged (non-shop) key: token3 present but these are ItemLot ids, not shop rows.
        // key_shop_rows still parses them; callers gate on token1 (key_flag) first.
        assert_eq!(
            key_shop_rows("2,1:60110:100000,100001:"),
            vec![100000, 100001]
        );
        // No token3 -> empty.
        assert!(key_shop_rows("100000,0:0000060510::").is_empty());
        assert!(key_shop_rows("100000,0").is_empty());
    }

    #[test]
    fn resolves_shop_slot_to_stock_flag() {
        // The real example from the handoff: shop key -> row 100200 -> its
        // ShopLineupParam.eventFlag_forStock. Verified from
        // elden_ring_artifacts/vanilla_er/vanilla_er/ShopLineupParam.csv:
        //   ID=100200 ... eventFlag_forStock=120000  (row read directly from the CSV)
        const ROW_100200_FLAG: u32 = 120000;
        let row_flags: HashMap<u32, u32> = [(100200u32, ROW_100200_FLAG)].into_iter().collect();
        let sd = json!({
            "locationIdsToKeys": {
                "7001": "100000,0:0000000000:100200:",   // shop slot -> row 100200
                "7002": "2,1:60110:100000,100001:",       // flagged (token1!=0) -> NOT a shop, skipped here
                "7003": "1,0:0000000000:999999:",         // shop row absent from table -> unresolved
            }
        });
        let m = shop_flags_from_keys(&sd, &row_flags);
        assert_eq!(m.len(), 1);
        assert_eq!(m.get(&7001), Some(&ROW_100200_FLAG)); // 120000
        assert!(!m.contains_key(&7002)); // flagged slot owned by location_flags_from_keys
        assert!(!m.contains_key(&7003)); // no known flag for row 999999 -> skipped
    }

    #[test]
    fn targets_fallback_resolves_what_token3_cannot() {
        // The measured foreign shape (synthetic ids): a boss-armor shop slot whose token3 is
        // ONLY a precondition flag + shop-range BASE id (neither in `row_flags`), with the
        // concrete row riding the targets table as "shop:NNNN". The fallback resolves it; a
        // slot with NO targets entry stays unpolled (the 64-slot known limit).
        let row_flags: HashMap<u32, u32> = [(600100u32, 640001u32)].into_iter().collect();
        let sd = json!({
            "locationIdsToKeys": {
                "9101": "555000,0:0000000000:9143,101500:",  // token3: precond + range base
                "9102": "555000,0:0000000000:9143,101500:",  // same shape, no targets entry
            },
            // NB the REAL emitted key carries a trailing space (module doc).
            "locationIdsToTargets ": {
                "9101": ["lot:12345", "shop:600100"],        // lot: skipped, shop: resolves
            }
        });
        let m = shop_flags_from_keys(&sd, &row_flags);
        assert_eq!(m.get(&9101), Some(&640001u32));
        assert!(
            !m.contains_key(&9102),
            "nothing usable anywhere -> unpolled, not guessed"
        );
        assert_eq!(m.len(), 1);
    }

    #[test]
    fn token3_stays_the_primary_path_over_targets() {
        // When token3 already names a flagged row, the targets entry must not override it --
        // byte-for-byte the pre-fallback behavior.
        let row_flags: HashMap<u32, u32> = [(600100u32, 640001u32), (600200u32, 640002u32)]
            .into_iter()
            .collect();
        let sd = json!({
            "locationIdsToKeys":     { "9110": "555000,0:0000000000:600100:" },
            "locationIdsToTargets ": { "9110": ["shop:600200"] },
        });
        let m = shop_flags_from_keys(&sd, &row_flags);
        assert_eq!(m.get(&9110), Some(&640001u32), "token3 row wins");
    }

    #[test]
    fn targets_tolerates_both_key_spellings_and_a_bare_string() {
        let row_flags: HashMap<u32, u32> = [(600100u32, 640001u32)].into_iter().collect();
        // Space-free spelling (the future typo fix) works...
        let sd = json!({
            "locationIdsToKeys":    { "9120": "555000,0:0000000000:9143:" },
            "locationIdsToTargets": { "9120": ["shop:600100"] },
        });
        assert_eq!(
            shop_flags_from_keys(&sd, &row_flags).get(&9120),
            Some(&640001u32)
        );
        // ...and a bare-string targets value (the source's un-normalized one-element tuple).
        let sd = json!({
            "locationIdsToKeys":     { "9121": "555000,0:0000000000:9143:" },
            "locationIdsToTargets ": { "9121": "shop:600100" },
        });
        assert_eq!(
            shop_flags_from_keys(&sd, &row_flags).get(&9121),
            Some(&640001u32)
        );
    }

    #[test]
    fn shop_and_location_maps_are_disjoint() {
        // location_flags_from_keys takes the flagged slots; shop_flags_from_keys takes the
        // token1==0 shop slots. The same slot_data feeds both; no key appears in both maps.
        let row_flags: HashMap<u32, u32> = [(100200u32, 120000u32)].into_iter().collect();
        let sd = json!({
            "locationIdsToKeys": {
                "8001": "100000,0:0000060510::",          // flagged -> 60510 (location map)
                "8002": "100000,0:0000000000:100200:",    // shop    -> 120000 (shop map)
            }
        });
        let loc = location_flags_from_keys(&sd);
        let shop = shop_flags_from_keys(&sd, &row_flags);
        assert_eq!(loc.get(&8001), Some(&60510u32));
        assert!(!loc.contains_key(&8002));
        assert_eq!(shop.get(&8002), Some(&120000u32));
        assert!(!shop.contains_key(&8001));
        // Disjoint keysets: merging is a clean union.
        assert!(loc.keys().all(|k| !shop.contains_key(k)));
    }

    #[test]
    fn precondition_flags_in_token3_are_skipped_and_the_row_wins() {
        // Foreign shop keys can carry a boss-achievement PRECONDITION flag before the row:
        // `<lot>,<n>:0000000000:<precondFlag>,<row>:`. The precondition is an event flag, not a
        // ShopLineupParam row, so it is never in `row_flags` and is naturally skipped; the first
        // token3 entry PRESENT in the table wins. All ids here are HAND-WRITTEN synthetic values
        // of the observed shapes (provenance: never the foreign world's content).
        let row_flags: HashMap<u32, u32> = [(600100u32, 640001u32), (600200u32, 640002u32)]
            .into_iter()
            .collect();
        let sd = json!({
            "locationIdsToKeys": {
                "9001": "555000,0:0000000000:4242,600100:",   // precond 4242 skipped -> row 600100
                "9002": "555000,0:0000000000:600200,600100:", // two live rows -> FIRST present wins
                "9003": "555000,0:0000000000:4242:",          // ONLY a non-row (range-base class) -> unpolled
            }
        });
        let m = shop_flags_from_keys(&sd, &row_flags);
        assert_eq!(m.get(&9001), Some(&640001u32));
        assert_eq!(m.get(&9002), Some(&640002u32)); // token3 order decides, not table order
        assert!(!m.contains_key(&9003)); // refusing to answer beats polling a bogus flag
        assert_eq!(m.len(), 2);
    }

    #[test]
    fn every_observed_key_shape_parses() {
        // One synthetic key per shape observed in the foreign key grammar
        // `<lot>,<n>:<flag10>:<refs>:` -- flagged with empty/one/two refs, and the all-zeros
        // token1 shop marker with one/mixed refs. Each shape either yields a flag (token1) or
        // defers to the shop path; no shape panics or misparses.
        assert_eq!(key_flag("100000,0:0000640001::"), Some(640001)); // N,N:F::
        assert_eq!(key_flag("100000,1:0000640001:200300:"), Some(640001)); // N,N:F:N:
        assert_eq!(key_flag("100000,1:0000640001:200300,200301:"), Some(640001)); // N,N:F:N,N:
        assert_eq!(key_flag("555000,0:0000000000:600100:"), None); // shop marker, one ref
        assert_eq!(key_flag("555000,0:0000000000:4242,600100:"), None); // shop marker, mixed refs
        assert_eq!(
            key_shop_rows("555000,0:0000000000:4242,600100:"),
            vec![4242, 600100]
        );
    }

    // --- shoplineup_flags.json loading ----------------------------------------------------

    #[test]
    fn loads_the_generators_rendering_and_filters_it() {
        // The EXACT rendering tools/gen_shoplineup_flags.py (apworld repo) writes: one
        // `"row": flag` entry per line, LF line endings. Rows/flags here are REAL vanilla
        // param rows cited from ShopLineupParam.csv (100000 -> 100000, 100200 -> 120000),
        // plus synthetic junk entries proving the tolerant walk: zero flags and non-numeric
        // keys are dropped, trailing NUL padding (a shrinking overwrite) is tolerated.
        let p = std::env::temp_dir().join(format!(
            "shoplineup_flags_render_{}.json",
            std::process::id()
        ));
        std::fs::write(
            &p,
            "{\n\"100000\": 100000,\n\"100200\": 120000,\n\"600200\": 0,\n\"junk\": 7\n}\n\u{0}\u{0}",
        )
        .unwrap();
        let t = load_shoplineup_flags(&p);
        std::fs::remove_file(&p).ok();
        assert_eq!(t.get(&100000), Some(&100000u32));
        assert_eq!(t.get(&100200), Some(&120000u32));
        assert!(!t.contains_key(&600200)); // zero flag = no check signal -> dropped
        assert_eq!(t.len(), 2); // "junk" key skipped, not fatal
    }

    #[test]
    fn missing_or_garbage_table_degrades_to_empty() {
        // Absent file, non-JSON, and wrong-shape JSON all yield an EMPTY table (shops stay
        // unresolved) -- never a panic. core.rs logs armed/inert off this emptiness.
        let p = std::env::temp_dir().join(format!(
            "shoplineup_flags_garbage_{}.json",
            std::process::id()
        ));
        std::fs::remove_file(&p).ok();
        assert!(load_shoplineup_flags(&p).is_empty()); // missing file
        std::fs::write(&p, "not json at all").unwrap();
        assert!(load_shoplineup_flags(&p).is_empty()); // unparseable
        std::fs::write(&p, "[600100, 640001]").unwrap();
        assert!(load_shoplineup_flags(&p).is_empty()); // valid JSON, not an object
        std::fs::remove_file(&p).ok();
    }

    #[test]
    fn loaded_table_drives_shop_resolution_end_to_end() {
        // File -> load_shoplineup_flags -> shop_flags_from_keys: the whole shop path with no
        // game and no net. Real vanilla row 100200 (eventFlag_forStock=120000, cited from
        // ShopLineupParam.csv); synthetic key of the mixed precondition+row shape.
        let p =
            std::env::temp_dir().join(format!("shoplineup_flags_e2e_{}.json", std::process::id()));
        std::fs::write(&p, "{\n\"100200\": 120000\n}\n").unwrap();
        let table = load_shoplineup_flags(&p);
        std::fs::remove_file(&p).ok();
        let sd = json!({
            "locationIdsToKeys": { "9100": "555000,0:0000000000:4242,100200:" }
        });
        let m = shop_flags_from_keys(&sd, &table);
        assert_eq!(m.get(&9100), Some(&120000u32));
        assert_eq!(m.len(), 1);
    }

    #[test]
    fn absent_shop_table_or_keys_is_empty() {
        let row_flags: HashMap<u32, u32> = [(100200u32, 120000u32)].into_iter().collect();
        // No locationIdsToKeys -> empty.
        assert!(shop_flags_from_keys(&json!({}), &row_flags).is_empty());
        // Keys present but empty row_flags table -> nothing resolves.
        let sd = json!({ "locationIdsToKeys": { "1": "1,0:0000000000:100200:" } });
        assert!(shop_flags_from_keys(&sd, &HashMap::new()).is_empty());
    }
}
