#!/usr/bin/env python3
"""Generate static candidate identities from the world registry (never corroboration).

Run with --world-dir pointing at the world checkout containing
export_mfg_check_registry.py. --check refuses drift without writing.
"""
import argparse
import hashlib
import importlib.util
from pathlib import Path


def rust_string(value):
    if not isinstance(value, str):
        raise ValueError("Catalog name must be text")
    escaped = []
    for char in value:
        if char in ('"', chr(92)):
            escaped.append(chr(92) + char)
        elif ord(char) < 32 or ord(char) == 127:
            escaped.append(chr(92) + "u{" + format(ord(char), "x") + "}")
        else:
            escaped.append(char)
    return '"' + ''.join(escaped) + '"'


def bounded(value, low, high, label):
    if type(value) is not int or not low <= value <= high:
        raise ValueError(f"{label} outside supported Rust integer range: {value!r}")
    return value


def render(world):
    source = world / "tools/export_mfg_check_registry.py"
    spec = importlib.util.spec_from_file_location("mfg_registry", source)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    registry = module.build(world)
    rows = set()
    flags = set()
    for check in registry["checks"]:
        flag = bounded(check["original_acquisition_flag"], 1, 2**32 - 1, "flag")
        ap_id = bounded(check["ap_id"], -(2**63), 2**63 - 1, "AP ID")
        flags.add((flag, ap_id))
        for lot in check["source_identity"]["item_lots"]:
            if lot["table"] not in ("map", "enemy"):
                raise ValueError("Unknown lot table: " + repr(lot["table"]))
            bounded(lot["row_id"], 0, 2**32 - 1, "lot row")
            rows.add((1 if lot["table"] == "map" else 2, lot["row_id"], flag, ap_id))
    lines = ["// Generated by tools/export_mfg_match_table.py; do not edit.",
             "// Candidate acquisition-flag groups; not independent corroboration."]
    for name in (*module.INPUTS, "tools/export_mfg_check_registry.py"):
        digest = hashlib.sha256((world / name).read_bytes()).hexdigest()
        lines.append(f"// SHA256 {name}: {digest}")
    lines.append("pub(super) static LOTS: &[(u32, u32, u32, i64)] = &[")
    lines.extend(f"    ({t}, {r}, {f}, {a})," for t, r, f, a in sorted(rows))
    lines.append("];\n")
    lines.append("pub(super) static FLAGS: &[(u32, i64)] = &[")
    lines.extend(f"    ({f}, {a})," for f, a in sorted(flags))
    lines.append("];\n")
    lines.append("#[rustfmt::skip]")
    lines.append("pub(super) static NAMES: &[(i64, &str)] = &[")
    lines.extend(f"    ({check['ap_id']}, {rust_string(check['name'])}),"
                 for check in sorted(registry["checks"], key=lambda c: c["ap_id"]))
    lines.append("];\n")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--world-dir", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[1]
                        / "crates/er-logic/src/mfg_match_data.rs")
    args = parser.parse_args()
    output = args.out
    text = render(args.world_dir)
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != text:
            parser.error("MFG identity table differs; regenerate from the intended world checkout")
    else:
        output.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
