"""Generate acquisition-to-native-defeat identities from committed world datamines."""
import argparse
import ast
import hashlib
from pathlib import Path


def generate(world: Path) -> str:
    combined = {}
    provenance = []
    for filename, constant in [('boss_reward_lots.py', 'BOSS_REWARD_DEFEAT'), ('boss_drops.py', 'BOSS_DROP_ENTITY')]:
        source = world / 'greenfield' / 'eldenring' / filename
        raw = source.read_bytes()
        assignments = [n for n in ast.parse(raw).body if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == constant for t in n.targets)]
        if len(assignments) != 1:
            raise ValueError('Expected one literal ' + constant)
        mapping = ast.literal_eval(assignments[0].value)
        for acquisition, defeat in mapping.items():
            if type(acquisition) is not int or type(defeat) is not int or not (0 < acquisition <= 0xFFFFFFFF and 0 < defeat <= 0xFFFFFFFF):
                raise ValueError('Invalid flag identity')
            if acquisition in combined and combined[acquisition] != defeat:
                raise ValueError('Conflicting acquisition flag: ' + str(acquisition))
            combined[acquisition] = defeat
        provenance.append('// ' + filename + ' sha256=' + hashlib.sha256(raw).hexdigest())
    return '\n'.join(['// @generated by tools/export_mfg_boss_flags.py -- DO NOT EDIT.', *provenance,
                     'pub const ACQUISITION_DEFEAT: &[(u32, u32)] = &[',
                     *(f'    ({a}, {d}),' for a, d in sorted(combined.items())), '];', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--world', type=Path, required=True)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1] / 'crates/er-logic/src/mfg_boss_flags_data.rs')
    args = parser.parse_args()
    args.output.write_text(generate(args.world), encoding='utf-8')
